### PR TITLE
Absolutize filter

### PR DESCRIPTION
**Pull request by selectnull**
I've added absolutize as filter along with template tags. README has been updated with examples and reason why sometimes filter works where tag doesn't.

### CODE REVIEW

**Comment by acatton** [comment]
Good catch @selectnull !

I don't see any reason why absolutize should be tag and not a filter. Could you add a deprecation warning on the tag. We will remove it in the future.

Thanks ;) .

**Comment by selectnull** [comment]
Actually, I'm against deprecating absolutize as a tag. What's more, I would propose that it be extended to support `as` tags, eg:

```
{% absolutize someobject.get_absolute_url as url %}
```

and then you can use `url` as variable.

**Comment by selectnull** [comment]
Anyway, it works both as tag and filter, why deprecate it? :)

**Comment by acatton** [comment]
@selectnull The [zen of python](https://www.python.org/dev/peps/pep-0020/) says _There should be one – and preferably only one – obvious way to do it._
- If you have a tag and a filter, now there are two ways to do the same thing.
- One of them should go away
- The filter works everywhere in `{% if url|absolutize %}` and so on...
- Why not remove the tag, it doesn't add any value whatsoever?

**Comment by acatton** [comment]
See e61be2b25705

**Comment by selectnull** [comment]
@acatton What about _One shall not break backward compatibility when software version is greater than 1_

Oh wait, Python 3... ;)

Never mind, since you've already decided, it's ok. When do you plan to upload to pypi?

**Comment by acatton** [comment]
@selectnull for now can you install from source. We might do a new release within the next month.

Thanks.

**Pull request merged**
